version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=receipts
      - POSTGRES_PASSWORD=receipts
      - POSTGRES_DB=receipts
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  db_data: